---
networks:
  homelab:
    external: true

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    hostname: "gitlab.vflorio.com"
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab-https.rule=Host(`gitlab.vflorio.com`)
      - traefik.http.routers.gitlab-https.entrypoints=websecure
      - traefik.http.routers.gitlab-https.tls=true
      - traefik.http.routers.gitlab-https.tls.certresolver=cloudflare
      - traefik.http.services.gitlab-service.loadbalancer.server.port=80
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.vflorio.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['backup_upload_remote_directory'] = 's3-backup-bucket'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.vflorio.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "gitlab@localhost"
        gitlab_rails['smtp_password'] = "EMAILPASSWORD"
        gitlab_rails['smtp_domain'] = "localhost"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - homelab

