#########################################################################
#########################################################################
#
# Filename: traefik.yaml        Traefik Static Configuration File
#
#########################################################################
#########################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO    # Options are:  TRACE , DEBUG , INFO , WARN , ERROR , FATAL , and PANIC

accessLog:
  filePath: /var/log/access.log
  format: json

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      tls:
        options: default
        certResolver: letsencrypt
        domains:
          - main: vflorio.com
            sans:
              - "*.vflorio.com"
  metrics:
    address: :8082

metrics:
  prometheus:
    entryPoint: metrics
    manualRouting: true
    headerLabels:
      useragent: User-Agent
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
  consul:
    rootKey: "traefik"
    endpoints:
      - "consul:8500"
    pollInterval: "5s"
    watch: true
    exposedByDefault: false
  consulCatalog:
    prefix: traefik
    exposedByDefault: false
    endpoints:
      - "consul:8500"
    watch: true
    connectAware: true
    pollInterval: "5s"
    stale: false
    defaultRule: "Host(`{{ normalize .Name }}.vflorio.com`)"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme.json
      keyType: EC384
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
        propagation:
          delayBeforeChecks: 2s

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
