#########################################################################
#########################################################################
#
# Filename: traefik.yaml        Traefik Static Configuration File
#
# Replace all "vflorio.com" values with your domain name
#
#  i.e.   - main: vflorio.com
#           sans:
#             - "*.vflorio.com"
#
#########################################################################
#########################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: INFO    # Options are:  TRACE , DEBUG , INFO , WARN , ERROR , FATAL , and PANIC

accessLog:
  filePath: /var/log/access.log
  format: json

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: secureweb
          scheme: https
          permanent: true
  secureweb:
    address: :443
    http:
      tls:
        options: default
        certResolver: cloudflare
        domains:
          - main: vflorio.com
            sans:
              - "*.vflorio.com"
  metrics:
    address: :8082

metrics:
  prometheus:
    entryPoint: metrics
    manualRouting: true
    headerLabels:
      useragent: User-Agent
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: floriovincenzo98@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
