services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/home/coder/.config
      - ./projects:/home/coder/projects
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD:-changeme}
    user: "1000:1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.srv-prod-1.intranet.vflorio.com`)"
      - "traefik.http.routers.code-server.entrypoints=web"
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"
    networks:
      - homelab

networks:
  homelab:
    external: true