services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
      - "8920:8920" # HTTPS
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/hdd-media/jellyfin:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.srv-prod-1.intranet.vflorio.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.srv-prod-1.intranet.vflorio.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - homelab

networks:
  homelab:
    external: true