---
networks:
  homelab:
    external: true

volumes:
  semaphore_config:
    driver: local
    
services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    volumes:
      - semaphore_config:/etc/semaphore:rw
      - ./data:/data:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.semaphore-https.entrypoints=websecure
      - traefik.http.routers.semaphore-https.rule=Host(`semaphore.srv-prod-0.intranet.vflorio.com`)
      - traefik.http.routers.semaphore-https.tls=true
      - traefik.http.routers.semaphore-https.tls.certresolver=cloudflare
      - traefik.http.services.semaphore.loadbalancer.server.port=3000
    networks:
      - homelab
    restart: unless-stopped


