---
networks:
  homelab:
    external: true

services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PUBLIC_DNS: domain
    networks:
      - homelab
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio-https.entrypoints=websecure
      - traefik.http.routers.drawio-https.rule=Host(`drawio.srv-prod-1.intranet.vflorio.com`)
      - traefik.http.routers.drawio-https.tls=true
      - traefik.http.routers.drawio-https.tls.certresolver=cloudflare
      - traefik.http.services.drawio-service.loadbalancer.server.port=8080
