version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_HOSTNAME=${TAILSCALE_HOSTNAME}
      - TS_ROUTES=${TAILSCALE_ROUTES}
      - TS_EXTRA_ARGS=${TAILSCALE_EXTRA_ARGS}
      - TS_STATE_DIR=${TAILSCALE_STATE_DIR}
      - TS_USERSPACE=${TAILSCALE_USERSPACE}
      - TS_ACCEPT_DNS=${TAILSCALE_ACCEPT_DNS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      - "traefik.enable=false"