- hosts: "{{ hosts }}"

  tasks:

    - name: Copy all files from local_project_dir to remote_project_dir
      copy:
        src: "{{ local_project_dir }}/"
        dest: "{{ remote_project_dir }}/"
        mode: '0644'
        force: yes
        remote_src: no
        #become: yes  # Esegue il task con privilegi di amministratore

    - name: Deploy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_dir }}"
        files:
          - docker-compose.yaml
        state: present
        pull: policy
        remove_orphans: true
