########################################################################################################################################################################################################
# GATEWAY SERVER
########################################################################################################################################################################################################
- 🌐 Gateway:
    - Authentik:
        icon: authentik.png
        href: https://auth.vflorio.com
        description: Authentication & SSO
        
    - Crowdsec:
        icon: crowdsec.png
        href: https://crowdsec.vflorio.com
        description: Security & Bot Protection
        
    - Headscale:
        icon: headscale.png
        href: https://headscale.vflorio.com
        description: VPN/Remote Access
        
    - Traefik:
        icon: traefik.png
        href: https://traefik.vflorio.com
        description: Reverse Proxy & TLS Management

########################################################################################################################################################################################################
# MANAGEMENT SERVER
########################################################################################################################################################################################################
- 📊 Management:
    - Grafana:
        icon: grafana.png
        href: https://grafana.vflorio.com
        container: grafana
        description: Monitoring Dashboards
        widget:
          type: grafana
          url: https://grafana.vflorio.com
          key: [REDACTED-KEY]

    - Guacamole:
        icon: guacamole.png
        href: https://guacamole.vflorio.com
        container: guacamole
        description: Remote Desktop Gateway

    - Homepage:
        icon: homepage.png
        href: https://home.vflorio.com
        container: homepage
        description: Dashboard & Services
        
    - Portainer:
        icon: portainer.png
        href: https://portainer.vflorio.com
        container: portainer
        description: Container Management
        widget:
          type: portainer
          url: https://portainer.vflorio.com
          env: 2
          key: [REDACTED-KEY]
          fields: ["running", "stopped"]

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.vflorio.com
        description: Metrics Collection

    - Semaphore:
        icon: semaphore.png
        href: https://semaphore.vflorio.com
        container: semaphore
        description: Ansible UI & Automation

########################################################################################################################################################################################################
# MEDIA SERVER
########################################################################################################################################################################################################
- 🎬 Media - Streaming:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.vflorio.com
        container: jellyfin
        description: Media Streaming Library
        widget:
          type: jellyfin
          url: https://jellyfin.vflorio.com
          key: [REDACTED-KEY]
          enableBlocks: true
          enableNowPlaying: true
          fields: ["movies", "series", "songs"]

    - Emby:
        icon: emby.png
        href: https://emby.vflorio.com
        container: emby
        description: Emby Media Streaming
        widget:
          type: emby
          url: https://emby.vflorio.com
          key: [REDACTED-KEY]
          enableBlocks: true
          enableNowPlaying: true

- 🎬 Media - Download:
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.vflorio.com
        container: qbittorrent
        description: Torrent Download Client
        widget:
          type: qbittorrent
          url: https://qbittorrent.vflorio.com
          key: [REDACTED-KEY]
          fields: ["leech", "seed", "download"]

    - SABnzbd:
        icon: sabnzbd.png
        href: https://sabnzbd.vflorio.com
        container: sabnzbd
        description: Usenet Download Client
        widget:
          type: sabnzbd
          url: https://sabnzbd.vflorio.com
          key: [REDACTED-KEY]
          fields: ["rate", "queue", "timeleft"]

- 🎬 Media - Management:
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.vflorio.com
        container: bazarr
        description: Subtitle Management
        widget:
          type: bazarr
          url: https://bazarr.vflorio.com
          key: [REDACTED-KEY]

    - Filebot:
        icon: filebot.png
        href: https://filebot.vflorio.com
        container: filebot
        description: File Organization & Renaming

    - Jellyseerr:
        icon: jellyseerr.png
        href: https://jellyseerr.vflorio.com
        container: jellyseerr
        description: Media Request Management
        widget:
          type: jellyseerr
          url: https://jellyseerr.vflorio.com
          key: [REDACTED-KEY]
          fields: ["pending", "approved", "available"]

    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.vflorio.com
        container: lidarr
        description: Music Library Automation
        widget:
          type: lidarr
          url: https://lidarr.vflorio.com
          key: [REDACTED-KEY]

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.vflorio.com
        container: prowlarr
        description: Indexer Management
        widget:
          type: prowlarr
          url: https://prowlarr.vflorio.com
          key: [REDACTED-KEY]
          fields: ["numberOfGrabs", "numberOfQueries"]

    - Radarr:
        icon: radarr.png
        href: https://radarr.vflorio.com
        container: radarr
        description: Movie Automation
        widget:
          type: radarr
          url: https://radarr.vflorio.com
          key: [REDACTED-KEY]
          fields: ["wanted", "queued", "missing"]

    - Readarr:
        icon: readarr.png
        href: https://readarr.vflorio.com
        container: readarr
        description: Book Library Automation
        widget:
          type: readarr
          url: https://readarr.vflorio.com
          key: [REDACTED-KEY]

    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.vflorio.com
        container: sonarr
        description: TV Series Automation
        widget:
          type: sonarr
          url: https://sonarr.vflorio.com
          key: [REDACTED-KEY]
          fields: ["wanted", "queued", "missing"]

    - Tdarr:
        icon: tdarr.png
        href: https://tdarr.vflorio.com
        container: tdarr
        description: Media Transcoding
        widget:
          type: tdarr
          url: https://tdarr.vflorio.com
          key: [REDACTED-KEY]

    - Unpackerr:
        icon: unpackerr.png
        href: https://unpackerr.vflorio.com
        description: Archive Extraction

########################################################################################################################################################################################################
# DEV SERVER
########################################################################################################################################################################################################
- 💻 Dev:
    - Coder:
        icon: code.png
        href: https://coder.vflorio.com
        description: VS Code in Browser

    - Container Registry:
        icon: docker.png
        href: https://registry.vflorio.com
        container: container-registry
        description: Private Docker Registry

    - Drawio:
        icon: drawio.png
        href: https://drawio.vflorio.com
        container: drawio
        description: Diagram Editor

    - Excalidraw:
        icon: excalidraw.png
        href: https://excalidraw.vflorio.com
        container: excalidraw
        description: Sketching & Whiteboard

    - Gitea:
        icon: gitea.png
        href: https://gitea.vflorio.com
        container: gitea
        description: Git Repository Server

    - Verdaccio:
        icon: npm.png
        href: https://verdaccio.vflorio.com
        container: verdaccio
        description: Private NPM Registry

########################################################################################################################################################################################################
# CLOUD SERVER
########################################################################################################################################################################################################
- ☁️ Cloud:
    - Immich:
        icon: immich.png
        href: https://immich.vflorio.com
        container: immich
        description: Photo & Video Library
        widget:
          type: immich
          url: https://immich.vflorio.com
          key: [REDACTED-KEY]
          version: 2
          fields: ["photos", "videos", "storage"]

    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.vflorio.com
        container: nextcloud
        description: Private Cloud Storage
        widget:
          type: nextcloud
          url: https://nextcloud.vflorio.com
          key: [REDACTED-KEY]
          fields: ["freespace", "numfiles"]

    - OnlyOffice:
        icon: onlyoffice.png
        href: https://onlyoffice.vflorio.com
        container: onlyoffice
        description: Office Suite

########################################################################################################################################################################################################
