---
- name: "Check if local directory exists for {{ app_name }}"
  stat:
    path: "{{ app_local_dir }}"
  delegate_to: localhost
  register: local_dir_check

- name: "Fall back to generic app directory if specific not found"
  set_fact:
    app_local_dir: "{{ project_base_dir }}/{{ app_name }}/"
  when: not local_dir_check.stat.exists

- name: "Deploy {{ app_name }} - Copy files"
  copy:
    src: "{{ app_local_dir }}"
    dest: "{{ app_remote_dir }}"
    mode: '0644'
    force: yes
    remote_src: no
  register: copy_result

- name: "Deploy {{ app_name }} - Start docker-compose"
  community.docker.docker_compose_v2:
    project_src: "{{ app_remote_dir }}"
    files:
      - docker-compose.yaml
    state: present
    pull: policy
    remove_orphans: true
  register: compose_result

- name: "Display result for {{ app_name }}"
  debug:
    msg: "{{ app_name }} deployed successfully to {{ app_remote_dir }}"
  when: compose_result is succeeded