services:
  bind9:
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Rome
    volumes:
      - ./config/:/etc/bind:rw
    network_mode: host
    restart: unless-stopped

