---
networks:
  homelab:
    external: true

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

services:
  passbolt:
    container_name: passbolt
    image: passbolt/passbolt:4.2.0-1-ce
    environment:
      - APP_FULL_BASE_URL=https://passbolt.srv-prod-1.intranet.vflorio.com
      - DATASOURCES_DEFAULT_HOST=passbolt-db
      - DATASOURCES_DEFAULT_DATABASE=${DATABASE}
      - DATASOURCES_DEFAULT_USERNAME=${USERNAME}
      - DATASOURCES_DEFAULT_PASSWORD=${PASSWORD}

    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passbolt-db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      traefik.enable: "true"
      traefik.http.routers.passbolt-https.middlewares: "passbolt-middleware@file"
      traefik.http.routers.passbolt-https.entrypoints: "websecure"
      traefik.http.routers.passbolt-https.rule: "Host(`passbolt.srv-prod-1.intranet.vflorio.com`)"
      traefik.http.routers.passbolt-https.tls: "true"
      traefik.http.routers.passbolt-https.tls.certresolver: "cloudflare"
    networks:
      - homelab
    restart: unless-stopped

  passbolt-db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - database_volume:/var/lib/mysql