###########################################################################
# HomeLab Cloud Server
# 
# IP: 192.168.1.194 (cloud.intranet.vflorio.com)
###########################################################################

networks:
  cloud:
    name: cloud
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:?err}
          gateway: ${DOCKER_GATEWAY:?err}

volumes:
  nextcloud-data:
  nextcloud-db:

###########################################################################
# CLOUD STORAGE SERVICES
###########################################################################

services: 
  ###########################################################################
  # Portainer - Docker Management
  ###########################################################################
  portainer-agent:
    container_name: portainer-agent
    image: "portainer/agent:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
    ports:
      - "${PORTAINER_AGENT_PORT:?err}:9001"
    #environment:
    #  AGENT_CLUSTER_ADDR: "192.168.1.171"  # IP srv-prod-1
    labels:
      - traefik.enable=true
      # ROUTERS
      - traefik.http.routers.portainer-agent.service=portainer-agent
      - traefik.http.routers.portainer-agent.entrypoints=websecure
      - traefik.http.routers.portainer-agent.rule=Host(`portainer-agent-cloud.${CLOUDFLARE_DNS_ZONE:?err}`) || Host(`portainer-agent-cloud.${INTRANET_DOMAIN:?err}`)
      - traefik.http.routers.portainer-agent.middlewares=authentik-forwardauth@file,security-headers@file,traefik-bouncer@file
      # SERVICES
      - traefik.http.services.portainer-agent.loadbalancer.server.scheme=http
      - traefik.http.services.portainer-agent.loadbalancer.server.port=9001
    # MIDDLEWARES
    networks:
      - cloud

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    volumes:
      - nextcloud-data:/var/www/html
    labels:
      traefik.enable: "true"
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"
      traefik.http.services.nextcloud.loadbalancer.server.scheme: "http"
      traefik.http.routers.nextcloud-https.entrypoints: "websecure"
      traefik.http.routers.nextcloud-https.rule: "Host(`nextcloud.srv-prod-1.intranet.vflorio.com`)"
      traefik.http.routers.nextcloud-https.tls: "true"
      traefik.http.routers.nextcloud-https.tls.certresolver: "cloudflare"
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=nextcloud-db
    restart: unless-stopped
    networks:
      - homelab

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=$MYSQL_USER
    restart: unless-stopped
    networks:
      - homelab

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./data:/var/www/onlyoffice/Data
      - ./logs:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET:-change-this-secret}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`office.srv-prod-1.intranet.vflorio.com`)"
      - "traefik.http.routers.onlyoffice.entrypoints=web"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
    networks:
      - homelab